version: '3.9'
services:
  rpc-server:
    build:
      context: ./rpc-server/server
      dockerfile: Dockerfile
    volumes:
      - "./rpc-server/server:/go/src/rpc-server"
    ports:
      - "8888:8888"
    environment:
      - SERVICE_NAME=rpc-server
      - SERVICE_TAGS=rpc

  http-server:
    build:
      context: ./http-server/server
      dockerfile: Dockerfile
    volumes:
      - "./http-server/server:/go/src/http-server"
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=http-server
      - SERVICE_TAGS=http
    depends_on:
      - rpc-server
